import Head from 'next/head'
import Image from 'next/image'
import { Text } from '@nextui-org/react'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Form from '../components/Form'
import QrCodeImage from '../components/QrCodeImage'

export default function Home() {

    const [userInput, setuserInput] = useState("");

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Text
                    h1
                    size={60}
                    css={{
                        textGradient: '45deg, $blue500 -20%, $pink500 50%'
                    }}
                    weight="bold"
                >The Ultimate </Text>
                <Text
                    h1
                    size={60}
                    css={{
                        textGradient: '45deg, $purple500 -20%, $pink500 100%'
                    }}
                    weight="bold"
                >
                    QR Code Generator
                </Text>
            </header>

            <Form
                userInput={userInput}
                setuserInput={setuserInput}
            />

            <QrCodeImage
                userInput={userInput}
                setuserInput={setuserInput}
            />
        </div>
    )
}
